# Generated by Django 4.2.20 on 2025-04-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedTranscriptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Supported transcript language',
                'verbose_name_plural': 'Supported transcript languages',
            },
        ),
        migrations.CreateModel(
            name='ProjectSupportedTranscriptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supportedtranscriptlanguage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'verbose_name': 'Project supported transcript language',
                'verbose_name_plural': 'Project supported transcript languages',
                'ordering': ['project', 'language'],
                'unique_together': {('project', 'language')},
            },
        ),
    ]
