# Generated by Django 4.2.20 on 2025-04-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supportedtranscriptlanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('input_node', 'Input'), ('output_node', 'Output'), ('ai_node', 'AI'), ('code_node', 'Code'), ('template_node', 'Template')], max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_data', to='api.node')),
            ],
        ),
    ]
